version: '3.3'

services:
  mysql:
    image: mysql:latest
    container_name: lesdb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mysql:/var/lib/mysql


networks:
  ecommerce-network:
    driver: bridge

volumes:
  mysql: